language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

  licenses:
    - '.+'

before_install:
- yes | sdkmanager "platforms;android-27"
before_script:
  - chmod +x gradlew
script:
  - ./gradlew test jacocoTestReportRelease
after_success:
  - bash <(curl -s https://codecov.io/bash)
